### ISSUE TITLE
pt3_drv: module verification failed

### ISSUE THREAD

**Issue by tomo0611** [m-tsudo/pt3#13]
Linux 5.3.1-050301-generic x86_64

![image](https://lh3.googleusercontent.com/-BkX-EjasPIPCZPHRGAREvqS-uGrn9nKrDZujo78lRFqUTFd2absphr-6ZUawLpraWR3__xIZ714WQh7pD8VofaZWnmz3hbxnkgxIv4kVGjgQoOgC-pLqS_w-8DSaBUxLA_k9dosuktmlDNrdqbdglIdZ8UnP3iNYJwEScTxlvsQpf-1ZIrUTCGopM8P5-In2nmfNGoGRBGplvFdORKi9mXBkxs4f-8mbbKgD0EB2h8WovdzKzawY5d5wmLU9cWOR-HwLv5OypTm57Hep1SeU_LcoNUpwyyPq0NTpyNSdW5k4wmiBakga1iadWhVqZhU2S_MW9xrydE8z7vr5lE60pZ1csB2qfZ6CbB97GfaAtlQPHiv-UrW3ruzWZbSJyYr53uTcqVR92n95SaPi4ktaSHTaYIpzimdSgvirL_SalqeX52xklHKhtReNXL8iGXCkhaqLhqOGZiTfAp7r1iKdU2jDMC3WSKb0WF8SBB5lzY6czbusFN0RhW28eihBNPNWaFV8IFykoDXvbz70NevMcepFh2iKmGGOGUPhfFyp-rzIBWWgTy3fFY2y6zq-mAfftWtJkuECxqIafL4OXbF2sNBODynzEYnKf2AQYHsxAHGBC179wLDiVAdqcarzbYv_PJzw0xZWqS8FWcsER0hcsEKL54EO6FO1jKO4L1wVkNmvlHn-eV7cXA=w613-h230-no)

```
[  172.300680] pt3_drv: loading out-of-tree module taints kernel.
[  172.300761] pt3_drv: module verification failed: signature and/or required key missing - tainting kernel
[  172.301185] PT3: pt3_drv 0.0.1rev112 2019-04-21
```
When I insert PX-W3U3, this message was logged and no px3video device in /dev/
Should I build kernel from source with [CONFIG_MODULE_SIG](https://stackoverflow.com/questions/24975377/kvm-module-verification-failed-signature-and-or-required-key-missing-taintin)?

**Comment by m-tsudo** [comment]
PX-W3U3 is NOT supported.
This driver support only PT-3.

**Comment by tomo0611** [comment]
Sorry i'll close this issue
