### ISSUE TITLE
Trying to compile on Raspberry Pi4 compute module

### ISSUE THREAD

**Issue by Corsaire01** [m-tsudo/pt3#14]
Hi,

I want to use a Raspberry Pi4 compute module on a i/o board to use a PT3, but I can't compile the module.
Here is the output of the error using Ubuntu 20.04 image:

root@ubuntu:~/pt3# make clean && make
make -C /lib/modules/`uname -r`/build M=`pwd` V=0 clean
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-1011-raspi'
  CLEAN   /root/pt3
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-1011-raspi'
eval `sed -e "s/\[0\]//" ./dkms.conf`; \
GREV=`git rev-list HEAD | wc -l 2> /dev/null`; \
if [ $GREV != 0 ] ; then \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}rev$GREV\"\n#define DRV_RELDATE \"`git show --date=short --format=%ad | sed -n '1p' 2> /dev/null`\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
else \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}\"\n#define DRV_RELDATE \"$PACKAGE_RELDATE\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
fi
make -C /lib/modules/`uname -r`/build M=`pwd` V=0 modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-1011-raspi'
  CC [M]  /root/pt3/pt3_pci.o
  CC [M]  /root/pt3/pt3_bus.o
  CC [M]  /root/pt3/pt3_i2c.o
  CC [M]  /root/pt3/pt3_tc.o
/root/pt3/pt3_tc.c: In function ‘tc_read’:
/root/pt3/pt3_tc.c:111:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  111 |  __u8 buf[size];
      |  ^~~~
/root/pt3/pt3_tc.c: In function ‘pt3_tc_read_tuner_without_addr’:
/root/pt3/pt3_tc.c:151:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  151 |  __u8 buf[size];
      |  ^~~~
/root/pt3/pt3_tc.c: In function ‘pt3_tc_read_tuner’:
/root/pt3/pt3_tc.c:238:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  238 |  __u8 buf[size];
      |  ^~~~
/root/pt3/pt3_tc.c: In function ‘create_pt3_tc’:
/root/pt3/pt3_tc.c:742:24: error: ‘-mgeneral-regs-only’ is incompatible with the use of floating-point types
  742 |  tc->master_clock_freq = 78;
      |  ~~~~~~~~~~~~~~~~~~~~~~^~~~
make[2]: *** [scripts/Makefile.build:290: /root/pt3/pt3_tc.o] Error 1
make[1]: *** [Makefile:1783: /root/pt3] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-1011-raspi'
make: *** [Makefile:12: pt3_drv.ko] Error 2

**Comment by m-tsudo** [comment]
Hi, Corsaire01
please, try compile in branch 'fix_issue_14'.

**Comment by Corsaire01** [comment]
Hi, did the test and it seems OK.

root@ubuntu:~/pt3# make clean && make
make -C /lib/modules/`uname -r`/build M=`pwd` V=0 clean
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-1011-raspi'
  CLEAN   /root/pt3
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-1011-raspi'
eval `sed -e "s/\[0\]//" ./dkms.conf`; \
GREV=`git rev-list HEAD | wc -l 2> /dev/null`; \
if [ $GREV != 0 ] ; then \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}rev$GREV\"\n#define DRV_RELDATE \"`git show --date=short --format=%ad | sed -n '1p' 2> /dev/null`\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
else \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}\"\n#define DRV_RELDATE \"$PACKAGE_RELDATE\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
fi
make -C /lib/modules/`uname -r`/build M=`pwd` V=0 modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-1011-raspi'
  CC [M]  /root/pt3/pt3_pci.o
  CC [M]  /root/pt3/pt3_bus.o
  CC [M]  /root/pt3/pt3_i2c.o
  CC [M]  /root/pt3/pt3_tc.o
/root/pt3/pt3_tc.c: In function ‘tc_read’:
/root/pt3/pt3_tc.c:111:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  111 |  __u8 buf[size];
      |  ^~~~
/root/pt3/pt3_tc.c: In function ‘pt3_tc_read_tuner_without_addr’:
/root/pt3/pt3_tc.c:151:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  151 |  __u8 buf[size];
      |  ^~~~
/root/pt3/pt3_tc.c: In function ‘pt3_tc_read_tuner’:
/root/pt3/pt3_tc.c:238:2: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
  238 |  __u8 buf[size];
      |  ^~~~
  CC [M]  /root/pt3/pt3_qm.o
  CC [M]  /root/pt3/pt3_mx.o
  CC [M]  /root/pt3/pt3_dma.o
  LD [M]  /root/pt3/pt3_drv.o
  MODPOST /root/pt3/Module.symvers
  CC [M]  /root/pt3/pt3_drv.mod.o
  LD [M]  /root/pt3/pt3_drv.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-1011-raspi'
