### ISSUE TITLE
ubuntu kernel 5.4.0-68 i2c runcode fail

### ISSUE THREAD

**Issue by azkintz** [m-tsudo/pt3#16]
5.4.0-58-generic working.
5.4.0-65-generic i2c runcode fail.

**Comment by Corsaire01** [comment]
You should give more details, like some log of the error.
詳細を提供いただけますか、エラーの際の出力など。

**Comment by azkintz** [comment]
少し混乱しています。 5.4.0-58-genericでも症状が再発し、現在は5.4.0-45-genericで動作しています。
ハードウェアの問題かもしれません。
エラー発生時のdmesgは次のようになっていました。
[    5.520638] PT3: device[0]=00000000xxxxxxxx
[    5.521014] PT3: card_number=0 channel=0
[    5.521467] PT3: card_number=0 channel=1
[    5.521948] PT3: card_number=0 channel=2
[    5.523673] PT3: card_number=0 channel=3
[    5.523864] PT3: Bus Mastering Enabled.
[    5.676848] PT3: fail i2c run_code status 0x32
[    5.684701] PT3: retry init_tuner
checksignalなどを実行するとPT3: fail i2c run_code status 0x32が繰り返し出力されていました。
もう少し追試します。

**Comment by azkintz** [comment]
再現はするもののH/Wの問題である可能性が排除できないため、CLOSEさせて頂きます。
お騒がせしてしまい申し訳ありません。
