### ISSUE TITLE
When executing make, the error "Invalid operand to binary operator >=" occurs

### ISSUE THREAD

**Issue by P-Kichi** [m-tsudo/pt3#17]
OS :  CentOS Linux release 7.9.2009 (Core)
Kernel : 3.10.0-1160.21.1.el7.x86_64
GCC : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

make 実行時

pt3_qm.c:529:29: エラー: 二項演算子 >= への無効な被演算子です (‘ktime_t’ と ‘long int’)

というエラーが発生します。
以下は make 実行結果です。
```
[root@centos pt3]# make
eval `sed -e "s/\[0\]//" ./dkms.conf`; \
GREV=`git rev-list HEAD | wc -l 2> /dev/null`; \
if [ $GREV != 0 ] ; then \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}rev$GREV\"\n#define DRV_RELDATE \"`git show --date=short --format=%ad | sed -n '1p' 2> /dev/null`\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
else \
        printf "#define DRV_VERSION \"${PACKAGE_VERSION}\"\n#define DRV_RELDATE \"$PACKAGE_RELDATE\"\n#define DRV_NAME \"${BUILT_MODULE_NAME}\"\n" > version.h; \
fi
make -C /lib/modules/`uname -r`/build M=`pwd` V=0 modules
make[1]: ディレクトリ `/usr/src/kernels/3.10.0-1160.21.1.el7.x86_64' に入ります
  CC [M]  /root/src/pt3/pt3_pci.o
  CC [M]  /root/src/pt3/pt3_bus.o
  CC [M]  /root/src/pt3/pt3_i2c.o
  CC [M]  /root/src/pt3/pt3_tc.o
  CC [M]  /root/src/pt3/pt3_qm.o
/root/src/pt3/pt3_qm.c: 関数 ‘pt3_qm_set_frequency’ 内:
/root/src/pt3/pt3_qm.c:529:29: エラー: 二項演算子 >= への無効な被演算子です (‘ktime_t’ と ‘long int’)
   if (ktime_sub(now, begin) >= (100 * NSEC_PER_USEC))
                             ^
make[2]: *** [/root/src/pt3/pt3_qm.o] エラー 1
make[1]: *** [_module_/root/src/pt3] エラー 2
make[1]: ディレクトリ `/usr/src/kernels/3.10.0-1160.21.1.el7.x86_64' から出ます
make: *** [pt3_drv.ko] エラー 2
```
==============================================================================

今年の初め（2021.01.01.頃）に実行した際はこの様なエラーは発生せず、問題なくビルドできました。
本日（2021.04.06.）、同一のハードに対してアップデートしてみようと思い立ち git pull にてソースコードを取得し make してみたところ、上記のエラーが発生しました。
git clone で取得し直してみたり、pt3-master.zip をダウンロード・解凍して試したりもしましたが、結果は同じでした。
尚、手持ちの古いソースコード（2019年11月辺りに取得したもの）からビルドしてみたところ、こちらは問題なくビルドできました。

ただ、他の方からの同様の報告は見かけませんので、当方の環境に起因する問題かも知れません。
つきましては、解決方法等をご教授頂きたく、よろしくお願い致します。

**Comment by m-tsudo** [comment]
ブランチfix_issuse_17を試してみてください。

**Comment by P-Kichi** [comment]
早速の返信ありがとうございます。
試させて頂きましたが、残念ながら解消されませんでした。

以下は make 実行時のエラーメッセージです。
`
/root/src/pt3/pt3_qm.c: 関数 ‘pt3_qm_set_frequency’ 内:
/root/src/pt3/pt3_qm.c:529:29: エラー: 二項演算子 >= への無効な被演算子です (‘ktime_t’ と ‘ktime_t’)
   if (ktime_sub(now, begin) >= ktime_set(0, 100 * NSEC_PER_USEC))
                             ^
`
コンパイラのバージョンが古いのが原因という可能性は考えられますでしょうか？

**Comment by m-tsudo** [comment]
原因は型の比較が厳密にされている事です。
※暗黙的型変換されない？
安易にktime_tの比較にすればよいのかと思いましたが違うようです。

ブランチfix_issue_17の最新を試してみてください。

**Comment by P-Kichi** [comment]
試してみたところ、無事にビルドする事ができました。
録画等の動作確認も一通り行いましたが、問題なく実行できました。
ご対応誠に有り難うございました。
本件はこれにて Close とさせて頂きます。
