### ISSUE TITLE
kernel 6.12でのビルド失敗

### ISSUE THREAD

**Issue by asukuru-01234** [m-tsudo/pt3#21]
OS: Ubuntu 24.04
Kernel: 6.12.0-061200-generic (6.12.0-061200.202411220723)

いつもお世話になっております。
Linux Kernel6.11までは正常動作していたのですが、6.12に上げたところドライバのビルドに失敗しましたので報告させていただきます。

エラーを確認したところ以下の個所が気になり、修正したところビルドが通りました。
```
/var/lib/dkms/pt3_drv/0.0.1/build/pt3_pci.c:863:25: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
  863 |         .llseek =       no_llseek,
      |                         ^~~~~~~~~
```

動作確認は引き続き行いますが、まず報告を優先すべく連絡させていただきました。
ご迷惑をおかけしますが、引き続きよろしくお願いいたします。

**Comment by asukuru-01234** [comment]
簡易確認では問題なさそうですが、ご確認いただけると幸いです。
どうぞよろしくお願いいたします。

**Comment by m-tsudo** [comment]
ご報告ありがとうございます。
ブランチfix_issue_21で修正してみました。
試して貰えますか。
